export const list_of_classes = [
  {
    date: "2021-09-07",
    duration: "1",
    intensityLevel: "low",
    location: "location 1",
    maxClassSize: "23",
    name: "tom",
    registeredAttendees: 0,
    startTime: "04:35",
    type: "type b",
  },
  {
    date: "2021-08-30",
    duration: "2",
    intensityLevel: "low",
    location: "location 2",
    maxClassSize: "55",
    name: "massy",
    registeredAttendees: 0,
    startTime: "16:40",
    type: "type a",
  },
  {
    date: "2021-09-07",
    duration: "3",
    intensityLevel: "low",
    location: "location 3",
    maxClassSize: "23",
    name: "tom",
    registeredAttendees: 0,
    startTime: "04:35",
    type: "type b",
  },
  {
    date: "2021-09-07",
    duration: "4",
    intensityLevel: "low",
    location: "location 4",
    maxClassSize: "23",
    name: "tom",
    registeredAttendees: 0,
    startTime: "04:35",
    type: "type b",
  },
  {
    date: "2021-09-07",
    duration: "5",
    intensityLevel: "low",
    location: "location 5",
    maxClassSize: "23",
    name: "tom",
    registeredAttendees: 0,
    startTime: "04:35",
    type: "type b",
  },
];
